version: "3.3"
services:
  nestjs:
    build: .
    image: facade
    ports:
     - "3000:3000"
    networks:
      - application
  mongodb:
    image: mongo
    ports:
     - "27017-27019:27017-27019"
    networks:
     - app
  postgres:
    image: postgres
    ports:
     - "5432:5432"
    networks:
     - app

networks: 
  app:
